#!/usr/bin/env bash

# Kill if already running
killall -9 sxhkd

# Launch keybindings daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# fix pointer
xsetroot -cursor_name left_ptr

# Toggle keyboard layouts
setxkbmap -option grp:win_space_toggle us &




bspc config border_width         2
bspc config window_gap           2
bspc config split_ratio          0.50

bspc config focused_border_color "#ff7a93"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# set wallpaper
feh --randomize --bg-fill /home/maku/Pictures/wallpapers/*
